import 'package:dummy_products/src/features/product/domain/product.dart';

final List<ProductModel> kTestProducts = [
  ProductModel(
    id: 2,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 3,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 4,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 5,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 6,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 7,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 8,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 9,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 10,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
  ProductModel(
    id: 11,
    title: 'iPhone X',
    price: 899,
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    stock: 34,
    discountPercentage: 17.94,
  ),
];
